#Make sure you have java 8 installed
FROM eclipse-temurin:8-jdk

EXPOSE 8080

WORKDIR /usr/src/app

# Copy content from the project to the image
COPY . .

# Build the project using maven wrapper
RUN ./mvnw package

# Run from generated jar-package
CMD java -jar ./target/docker-example-1.1.3.jar