version: '3.8'

services:

    example-frontend:
      build:
        context: example-frontend/
        dockerfile: Dockerfile_1.12
      environment:
        REACT_APP_BACKEND_URL: "${REACT_APP_BACKEND_URL:-http://localhost:8080}"
      ports:
        - '5000:5000'
      container_name: example-fronted-composed


    example-backend:
      build:
        context: example-backend/
        dockerfile: Dockerfile_1.13
      ports:
        - '8080:8080'
      container_name: example-backend-composed