version: '3.8'

services:

    simple-web-service:
      image: devopsdockeruh/simple-web-service
      container_name: composed-simple-web-server
      command: server
      ports:
        - '8080:8080'

