# Start from the following image:
FROM ubuntu:18.04

# Use /usr/src/app as our workdir. The following instructions will be executed in this location.
WORKDIR /usr/src/app

# Install curl
RUN apt-get update && apt-get install -y curl

# Copy the curler.sh file from this location to /usr/src/app/
COPY curler.sh .

# Alternatively, if we skipped chmod earlier, we can add execution permissions during the build.
RUN chmod +x curler.sh

# When running docker run the command will be ./curler.sh
CMD ./curler.sh
